version: "3.7"
services:


networks:
  peajemx-frontend-net:
    name: peajemx-frontend-net
    driver: bridge
  peajemx-services-net:
    name: peajemx-services-net
    driver: bridge
  npm:
    external: true