version: "3.7"
services:
  peajemx-frontend:
    build:
      context: .
      dockerfile: ./app-angular/Dockerfile
    container_name: peajemx-frontend
    restart: always
  peajemx-services:
    build: ./backend
    container_name: peajemx-services
    volumes:
      - ./backend:/app
      - /app/node_modules